import "./globals.css";
import type { Metadata } from "next";
import { Merriweather_Sans } from "next/font/google";
import NavBar from "./components/nav-bar";

const merriweather = Merriweather_Sans({
  variable: "--font-merriweather-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="es-ES">
        <body
          className={`${merriweather.className} antialiased`}
        >
          <NavBar />
          {children}
        </body>
      </html>
  );
}
